// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cover: typeof import('./../src/components/Cover.vue')['default']
    Dialog: typeof import('./../src/components/Dialog.vue')['default']
    ElSvgIcon: typeof import('./../src/components/ElSvgIcon.vue')['default']
    ImgUpload: typeof import('./../src/components/ImgUpload.vue')['default']
    MarkDownEdit: typeof import('./../src/components/MarkDownEdit.vue')['default']
    MdEditorV3Com: typeof import('./../src/components/MdEditorV3Com.vue')['default']
    MyChartComp: typeof import('./../src/components/charts/MyChartComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/icons/SvgIcon.vue')['default']
    Table: typeof import('./../src/components/Table.vue')['default']
    TestUnit: typeof import('./../src/components/TestUnit.vue')['default']
    Window: typeof import('./../src/components/Window.vue')['default']
  }
}
